// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-d72f800
//		go		go1.22.3
//	update:	1718880177
//	source: lmq.proto

package lmq

const (
	ServerName = "lmq"
)

const (
	RpcPathSetTopic      = "/SetTopic"
	RpcPathGetTopic      = "/GetTopic"
	RpcPathListTopic     = "/ListTopic"
	RpcPathDeleteTopic   = "/DeleteTopic"
	RpcPathSetChannel    = "/SetChannel"
	RpcPathGetChannel    = "/GetChannel"
	RpcPathDeleteChannel = "/DeleteChannel"
	RpcPathPub           = "/Pub"
	RpcPathBatchPub      = "/BatchPub"
	RpcPathPopMessage    = "/PopMessage"
	RpcPathFinishMessage = "/FinishMessage"
)
