// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-d72f800
//		go		go1.22.3
//	update:	1718880177
//	source: lmq.proto

package main

import (
	"github.com/lazygophers/lmq"
	"github.com/lazygophers/lmq/internal/impl"
	"github.com/lazygophers/lrpc"
)

var app = lrpc.NewApp(&lrpc.Config{})

var Routes = []*lrpc.Route{
	{
		Method:  "POST",
		Path:    lmq.RpcPathSetTopic,
		Handler: app.ToHandlerFunc(impl.SetTopic),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathGetTopic,
		Handler: app.ToHandlerFunc(impl.GetTopic),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathListTopic,
		Handler: app.ToHandlerFunc(impl.ListTopic),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathDeleteTopic,
		Handler: app.ToHandlerFunc(impl.DeleteTopic),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathSetChannel,
		Handler: app.ToHandlerFunc(impl.SetChannel),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathGetChannel,
		Handler: app.ToHandlerFunc(impl.GetChannel),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathDeleteChannel,
		Handler: app.ToHandlerFunc(impl.DeleteChannel),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathPub,
		Handler: app.ToHandlerFunc(impl.Pub),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathBatchPub,
		Handler: app.ToHandlerFunc(impl.BatchPub),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathPopMessage,
		Handler: app.ToHandlerFunc(impl.PopMessage),
		Extra: map[string]any{
			"role": "",
		},
	},
	{
		Method:  "POST",
		Path:    lmq.RpcPathFinishMessage,
		Handler: app.ToHandlerFunc(impl.FinishMessage),
		Extra: map[string]any{
			"role": "",
		},
	},
}
